name: NOAA NDBC Latest Observations
on:
  schedule:
    # https://github.blog/changelog/2019-11-01-github-actions-scheduled-jobs-maximum-frequency-is-changing/
    - cron: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat-noaa-ndbc.yml
      - ./NOAA-NDBC/postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt
          downloaded_filename: NOAA-NDBC/latest_obs.txt
          # postprocess: ./NOAA-NDBC/postprocess.ts
